# Generated by Django 5.0.1 on 2024-02-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0003_alter_instructor_uid_alter_meetingtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='uid',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
