# Generated by Django 5.0.1 on 2024-02-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0004_alter_instructor_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='r_number',
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='Default Room', max_length=20),
        ),
    ]
