# Generated by Django 5.0.1 on 2024-02-18 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0005_remove_room_r_number_room_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='pid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('8:00 - 10:00', '8:00 - 10:00'), ('10:00 - 12:00', '10:00 - 12:00'), ('12:00 - 2:00', '12:00 - 2:00'), ('2:00 - 4:00', '2:00 - 4:00'), ('4:00 - 6:00', '4:00 - 6:00')], default='11:00 - 12:00', max_length=50),
        ),
    ]
