# Generated by Django 5.0.1 on 2024-02-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0006_alter_meetingtime_pid_alter_meetingtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='pid',
            field=models.CharField(editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
