# Generated by Django 5.0.1 on 2024-02-18 20:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0007_alter_meetingtime_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='pid',
            field=models.CharField(editable=False, max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
