# Generated by Django 5.0.1 on 2024-02-24 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0009_section_level_alter_section_section_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtime',
            name='time',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.department'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='available_time_slots',
            field=models.ManyToManyField(related_name='available_instructors', to='SchedulerApp.meetingtime'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='preferred_time_slots',
            field=models.ManyToManyField(blank=True, related_name='preferred_instructors', to='SchedulerApp.meetingtime'),
        ),
        migrations.AddField(
            model_name='meetingtime',
            name='end_time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='meetingtime',
            name='start_time',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AlterField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(related_name='departments', to='SchedulerApp.course'),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.instructor')),
                ('meeting_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.meetingtime')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.room')),
            ],
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
