# Generated by Django 5.0.1 on 2024-02-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0010_remove_meetingtime_time_course_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.department'),
        ),
    ]
