# Generated by Django 5.0.1 on 2024-02-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0011_alter_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.department'),
        ),
    ]
