# Generated by Django 5.0.1 on 2024-02-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0013_alter_course_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('8:00 - 10:00', '8:00 - 10:00'), ('10:00 - 12:00', '10:00 - 12:00'), ('12:00 - 2:00', '12:00 - 2:00'), ('2:00 - 4:00', '2:00 - 4:00'), ('4:00 - 6:00', '4:00 - 6:00')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='available_time_slots',
        ),
        migrations.AddField(
            model_name='instructor',
            name='preferred_days',
            field=models.ManyToManyField(blank=True, to='SchedulerApp.day'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='preferred_time_slots',
            field=models.ManyToManyField(blank=True, to='SchedulerApp.timeslot'),
        ),
    ]
