# Generated by Django 5.0.1 on 2024-02-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0015_remove_instructor_preferred_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')], default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.department'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='preferred_days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='preferred_time_slots',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
