# Generated by Django 5.0.1 on 2024-02-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0016_course_level_alter_course_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Information Technology', 'Information Technology'), ('Computer Science', 'Computer Science'), ('Cyber Security', 'Cyber Security')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
