# Generated by Django 5.0.1 on 2024-02-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0019_delete_meetingtime_alter_lecture_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='duration',
        ),
    ]
