# Generated by Django 5.0.1 on 2024-02-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0020_remove_lecture_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
