# Generated by Django 5.0.1 on 2024-02-24 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0021_alter_lecture_lecture_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='lecture_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='meeting_time',
            field=models.CharField(blank=True, choices=[('8:00 - 10:00', '8:00 - 10:00'), ('10:00 - 12:00', '10:00 - 12:00'), ('12:00 - 2:00', '12:00 - 2:00'), ('2:00 - 4:00', '2:00 - 4:00'), ('4:00 - 6:00', '4:00 - 6:00')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SchedulerApp.room'),
        ),
    ]
