# Generated by Django 5.0.1 on 2024-02-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0023_alter_course_max_numb_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Information Technology', 'Information Technology'), ('Computer Science', 'Computer Science'), ('Cyber Security', 'Cyber Security')], max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(related_name='courses', to='SchedulerApp.department'),
        ),
    ]
