# Generated by Django 5.0.1 on 2024-02-27 10:02

from django.db import migrations

def set_default_day_for_lectures(apps, schema_editor):
    Lecture = apps.get_model('SchedulerApp', 'Lecture')
    for lecture in Lecture.objects.all():
        lecture.day_of_week = 'Monday'  # Or use your logic to determine the day
        lecture.save()

class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0026_lecture_day_of_week'),
    ]

    operations = [
        migrations.RunPython(set_default_day_for_lectures),

    ]
