# Generated by Django 5.0.1 on 2024-02-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0027_set_default_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
